# Generated by Django 5.0 on 2023-12-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='media/avatares/Captura_de_pantalla_2023-06-26_213713.png', upload_to='avatares'),
        ),
    ]
